# Generated by Django 4.1.7 on 2023-02-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_comment_delete_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="status",
        ),
    ]
